namespace AttendanceQR.Api;

/// <summary>
/// Stops an account that is still on a TEMPORARY PIN from using the API for anything except getting
/// off it.
///
/// A temp PIN is not a secret the employee chose. It is generated by an admin (bulk import, a PIN
/// reset, a forgot-PIN claim), read out over the phone or handed over on paper, and it sits in the
/// admin's screen and in whatever WhatsApp message carried it. Four digits, known to at least two
/// people and usually written down somewhere.
///
/// Until now the only thing standing between that PIN and a full session was the React router:
/// <c>ProtectedRoute</c> redirects to /set-pin while the "mcp" claim is set. That is a redirect in
/// the browser, not a rule on the server — the token handed out at login was an ordinary, fully
/// privileged, never-expiring one. Anyone who kept it (curl, the network tab, a saved response)
/// could read that employee's attendance indefinitely, and if the account was an admin's, run the
/// admin API with it. The employee's own act of choosing a PIN was the only thing that ended it, and
/// an employee who never opened the app never ended it at all.
///
/// So the gate lives here, on the server, and reads <c>Employee.MustChangePin</c> from the database
/// rather than the claim — fail-closed, and free, since that row is already read on every request to
/// check TokenVersion.
/// </summary>
public static class TemporaryPinGate
{
    /// <summary>Set on the request by OnTokenValidated when the caller is still on a temporary PIN.</summary>
    public const string ItemKey = "TempPin";

    /// <summary>
    /// The endpoints that still answer while on a temporary PIN. Deliberately tiny — an allowlist,
    /// so a new controller is closed by default rather than open until someone remembers this file.
    /// </summary>
    public static bool IsAllowedOnTemporaryPin(PathString path) =>
        // The way out: sets the employee's own PIN, clears the flag, and issues a fresh token.
        path.StartsWithSegments("/api/auth/set-initial-pin")
        // The other way out. It verifies the CURRENT PIN (the temporary one) before changing it, and
        // clears the flag too — an employee who reaches for "change my PIN" instead of the forced
        // screen must not hit a wall.
        || path.StartsWithSegments("/api/auth/change-password")
        // Not a session at all: the company's name, logo and colours, which the app needs to render
        // the "set your PIN" screen it is being sent to. Returns nothing about anybody.
        || path.StartsWithSegments("/api/tenant");

    /// <summary>
    /// 403 + <c>PinChangeRequired</c> for anything else. Not 401: the token is valid and the session
    /// is real — the client must stay signed in to be able to call set-initial-pin, and a 401 would
    /// bounce it to the login screen it just came from, into a loop it cannot leave.
    /// </summary>
    public static IApplicationBuilder UseTemporaryPinGate(this IApplicationBuilder app) =>
        app.Use(async (context, next) =>
        {
            if (context.Items.ContainsKey(ItemKey) && !IsAllowedOnTemporaryPin(context.Request.Path))
            {
                context.Response.StatusCode = StatusCodes.Status403Forbidden;
                await context.Response.WriteAsJsonAsync(new { error = "PinChangeRequired" });
                return;
            }

            await next();
        });
}
