#!/usr/bin/env python3
"""Regenerate ops/new-server/Caddyfile.maintenance from ./Caddyfile.

The maintenance variant must differ from production in EXACTLY two places — the api.qrlog.az and
api-test.qrlog.az blocks answer 503 instead of proxying — and nothing else, or the "frontend stays up
during the cutover window" promise silently breaks. Generating it (instead of hand-editing a copy)
is what keeps that true after any future Caddyfile change. Run from the repo root.
"""
import io, re, sys

src = io.open("Caddyfile", encoding="utf-8").read()
out = src
for host, upstream in (("api.qrlog.az", "backend:8080"), ("api-test.qrlog.az", "stg-backend:8080")):
    block_re = re.compile(r"(^" + re.escape(host) + r" \{\n)(.*?)(\n\}\n)", re.S | re.M)
    m = block_re.search(out)
    if not m or f"reverse_proxy {upstream}" not in m.group(2):
        sys.exit(f"Caddyfile layout changed: cannot find '{host}' block proxying to {upstream}")
    body = m.group(2).replace(
        f"\treverse_proxy {upstream}",
        "\t# MAINTENANCE: the API answers 503 and NOTHING else changes. No CORS headers on purpose —\n"
        "\t# the browser surfaces this as a thrown fetch, which is exactly the path that sends a scan\n"
        "\t# to the phone's offline queue (green card). Frontends, landing and static files keep\n"
        "\t# serving so an employee can still open the app and scan.\n"
        "\theader Retry-After \"1500\"\n"
        "\theader Content-Type \"application/json\"\n"
        "\trespond `{\"error\":\"Maintenance\",\"retryAfterSeconds\":1500}` 503")
    out = out[:m.start(2)] + body + out[m.end(2):]

header = ("# ===== CUTOVER MAINTENANCE VARIANT of ./Caddyfile =====\n"
          "# Generated by ops/new-server/make-maintenance-caddyfile.py — do not hand-edit. ONLY the api.qrlog.az\n"
          "# and api-test.qrlog.az blocks differ from ./Caddyfile: reverse_proxy → 503. Apply on the OLD host at\n"
          "# T+0 by copying over ./Caddyfile and force-recreating caddy; revert by restoring the original.\n\n")
io.open("ops/new-server/Caddyfile.maintenance", "w", encoding="utf-8", newline="\n").write(header + out)
print("ops/new-server/Caddyfile.maintenance regenerated")
