using AttendanceQR.Api;
using Microsoft.AspNetCore.Http;
using Xunit;

namespace AttendanceQR.Application.Tests;

/// <summary>
/// A temporary PIN is generated by an admin, read out over the phone or printed on a list, and known
/// to at least two people. Until this gate existed, logging in with one produced an ordinary,
/// never-expiring, fully privileged token — the forced "set your PIN" screen was a React redirect and
/// nothing more. Keep the token (curl, devtools, a saved response) and the temp PIN never stopped
/// being a full session; on an admin's account, a full admin session.
///
/// These pin the allowlist. It is deliberately tiny, and it is an ALLOWlist so that a controller
/// added next year is closed by default instead of open until somebody remembers this file.
/// </summary>
public class TemporaryPinGateTests
{
    [Theory]
    // The two ways off a temporary PIN. set-initial-pin is the forced screen; change-password is the
    // employee who went looking for it in the menu instead — it verifies the current (temporary) PIN
    // and clears the flag too, so it must not hit a wall.
    [InlineData("/api/auth/set-initial-pin")]
    [InlineData("/api/auth/change-password")]
    // The company's name, logo and colours. Needed to render the very screen the caller is being sent
    // to, and it reveals nothing about anybody.
    [InlineData("/api/tenant/branding")]
    public void The_way_out_stays_open(string path)
    {
        Assert.True(TemporaryPinGate.IsAllowedOnTemporaryPin(new PathString(path)));
    }

    [Theory]
    // Their own data — the reason the PIN is worth stealing at all.
    [InlineData("/api/attendance/my")]
    [InlineData("/api/employees/me")]
    // The scan. Blocked on purpose, and it does NOT contradict "a check-in is never blocked by
    // anything optional": choosing a PIN is not an optional check that might fail on a bad camera or
    // a weak GPS fix — it is ten seconds on a screen the app already forces, and it is what makes the
    // check-in theirs rather than anyone holding the paper the temp PIN was written on.
    [InlineData("/api/attendance/scan")]
    // And the part that made this a real finding rather than a tidy one: a temp PIN on an ADMIN's
    // account drove the admin API.
    [InlineData("/api/admin/employees")]
    [InlineData("/api/admin/reports/today")]
    [InlineData("/api/superadmin/tenants")]
    public void Everything_else_is_refused(string path)
    {
        Assert.False(TemporaryPinGate.IsAllowedOnTemporaryPin(new PathString(path)));
    }

    [Fact]
    public void A_path_that_merely_starts_with_an_allowed_one_is_not_allowed()
    {
        // StartsWithSegments, not StartsWith: "/api/tenants" (the super-admin registry) shares a
        // prefix with "/api/tenant" (public branding) and must not inherit its exemption.
        Assert.False(TemporaryPinGate.IsAllowedOnTemporaryPin(new PathString("/api/tenants")));
        Assert.False(TemporaryPinGate.IsAllowedOnTemporaryPin(new PathString("/api/auth/change-password-of-someone-else")));
    }

    [Fact]
    public void The_rest_of_auth_is_not_exempt_just_because_set_initial_pin_lives_there()
    {
        // The exemption is per endpoint, not per controller — /api/auth also holds the PIN-reset and
        // account routes, and a caller who has not chosen a PIN has no business in them.
        Assert.False(TemporaryPinGate.IsAllowedOnTemporaryPin(new PathString("/api/auth/forgot-pin")));
        Assert.False(TemporaryPinGate.IsAllowedOnTemporaryPin(new PathString("/api/auth")));
    }
}
